//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IETT_GUI.HatDurakGuzergah {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HatDurakGuzergah.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name DurakKodu from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDurak_XML", ReplyAction="*")]
        IETT_GUI.HatDurakGuzergah.GetDurak_XMLResponse GetDurak_XML(IETT_GUI.HatDurakGuzergah.GetDurak_XMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDurak_XML", ReplyAction="*")]
        System.Threading.Tasks.Task<IETT_GUI.HatDurakGuzergah.GetDurak_XMLResponse> GetDurak_XMLAsync(IETT_GUI.HatDurakGuzergah.GetDurak_XMLRequest request);
        
        // CODEGEN: Generating message contract since element name DurakKodu from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDurak_json", ReplyAction="*")]
        IETT_GUI.HatDurakGuzergah.GetDurak_jsonResponse GetDurak_json(IETT_GUI.HatDurakGuzergah.GetDurak_jsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDurak_json", ReplyAction="*")]
        System.Threading.Tasks.Task<IETT_GUI.HatDurakGuzergah.GetDurak_jsonResponse> GetDurak_jsonAsync(IETT_GUI.HatDurakGuzergah.GetDurak_jsonRequest request);
        
        // CODEGEN: Generating message contract since element name GetGaraj_XMLResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGaraj_XML", ReplyAction="*")]
        IETT_GUI.HatDurakGuzergah.GetGaraj_XMLResponse GetGaraj_XML(IETT_GUI.HatDurakGuzergah.GetGaraj_XMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGaraj_XML", ReplyAction="*")]
        System.Threading.Tasks.Task<IETT_GUI.HatDurakGuzergah.GetGaraj_XMLResponse> GetGaraj_XMLAsync(IETT_GUI.HatDurakGuzergah.GetGaraj_XMLRequest request);
        
        // CODEGEN: Generating message contract since element name GetGaraj_jsonResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGaraj_json", ReplyAction="*")]
        IETT_GUI.HatDurakGuzergah.GetGaraj_jsonResponse GetGaraj_json(IETT_GUI.HatDurakGuzergah.GetGaraj_jsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGaraj_json", ReplyAction="*")]
        System.Threading.Tasks.Task<IETT_GUI.HatDurakGuzergah.GetGaraj_jsonResponse> GetGaraj_jsonAsync(IETT_GUI.HatDurakGuzergah.GetGaraj_jsonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDurak_XMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDurak_XML", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.HatDurakGuzergah.GetDurak_XMLRequestBody Body;
        
        public GetDurak_XMLRequest() {
        }
        
        public GetDurak_XMLRequest(IETT_GUI.HatDurakGuzergah.GetDurak_XMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDurak_XMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DurakKodu;
        
        public GetDurak_XMLRequestBody() {
        }
        
        public GetDurak_XMLRequestBody(string DurakKodu) {
            this.DurakKodu = DurakKodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDurak_XMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDurak_XMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.HatDurakGuzergah.GetDurak_XMLResponseBody Body;
        
        public GetDurak_XMLResponse() {
        }
        
        public GetDurak_XMLResponse(IETT_GUI.HatDurakGuzergah.GetDurak_XMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDurak_XMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetDurak_XMLResult;
        
        public GetDurak_XMLResponseBody() {
        }
        
        public GetDurak_XMLResponseBody(System.Xml.Linq.XElement GetDurak_XMLResult) {
            this.GetDurak_XMLResult = GetDurak_XMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDurak_jsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDurak_json", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.HatDurakGuzergah.GetDurak_jsonRequestBody Body;
        
        public GetDurak_jsonRequest() {
        }
        
        public GetDurak_jsonRequest(IETT_GUI.HatDurakGuzergah.GetDurak_jsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDurak_jsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DurakKodu;
        
        public GetDurak_jsonRequestBody() {
        }
        
        public GetDurak_jsonRequestBody(string DurakKodu) {
            this.DurakKodu = DurakKodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDurak_jsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDurak_jsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.HatDurakGuzergah.GetDurak_jsonResponseBody Body;
        
        public GetDurak_jsonResponse() {
        }
        
        public GetDurak_jsonResponse(IETT_GUI.HatDurakGuzergah.GetDurak_jsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDurak_jsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDurak_jsonResult;
        
        public GetDurak_jsonResponseBody() {
        }
        
        public GetDurak_jsonResponseBody(string GetDurak_jsonResult) {
            this.GetDurak_jsonResult = GetDurak_jsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGaraj_XMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGaraj_XML", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.HatDurakGuzergah.GetGaraj_XMLRequestBody Body;
        
        public GetGaraj_XMLRequest() {
        }
        
        public GetGaraj_XMLRequest(IETT_GUI.HatDurakGuzergah.GetGaraj_XMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetGaraj_XMLRequestBody {
        
        public GetGaraj_XMLRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGaraj_XMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGaraj_XMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.HatDurakGuzergah.GetGaraj_XMLResponseBody Body;
        
        public GetGaraj_XMLResponse() {
        }
        
        public GetGaraj_XMLResponse(IETT_GUI.HatDurakGuzergah.GetGaraj_XMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGaraj_XMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetGaraj_XMLResult;
        
        public GetGaraj_XMLResponseBody() {
        }
        
        public GetGaraj_XMLResponseBody(System.Xml.Linq.XElement GetGaraj_XMLResult) {
            this.GetGaraj_XMLResult = GetGaraj_XMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGaraj_jsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGaraj_json", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.HatDurakGuzergah.GetGaraj_jsonRequestBody Body;
        
        public GetGaraj_jsonRequest() {
        }
        
        public GetGaraj_jsonRequest(IETT_GUI.HatDurakGuzergah.GetGaraj_jsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetGaraj_jsonRequestBody {
        
        public GetGaraj_jsonRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGaraj_jsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGaraj_jsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.HatDurakGuzergah.GetGaraj_jsonResponseBody Body;
        
        public GetGaraj_jsonResponse() {
        }
        
        public GetGaraj_jsonResponse(IETT_GUI.HatDurakGuzergah.GetGaraj_jsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGaraj_jsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGaraj_jsonResult;
        
        public GetGaraj_jsonResponseBody() {
        }
        
        public GetGaraj_jsonResponseBody(string GetGaraj_jsonResult) {
            this.GetGaraj_jsonResult = GetGaraj_jsonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : IETT_GUI.HatDurakGuzergah.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<IETT_GUI.HatDurakGuzergah.WebService1Soap>, IETT_GUI.HatDurakGuzergah.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IETT_GUI.HatDurakGuzergah.GetDurak_XMLResponse IETT_GUI.HatDurakGuzergah.WebService1Soap.GetDurak_XML(IETT_GUI.HatDurakGuzergah.GetDurak_XMLRequest request) {
            return base.Channel.GetDurak_XML(request);
        }
        
        public System.Xml.Linq.XElement GetDurak_XML(string DurakKodu) {
            IETT_GUI.HatDurakGuzergah.GetDurak_XMLRequest inValue = new IETT_GUI.HatDurakGuzergah.GetDurak_XMLRequest();
            inValue.Body = new IETT_GUI.HatDurakGuzergah.GetDurak_XMLRequestBody();
            inValue.Body.DurakKodu = DurakKodu;
            IETT_GUI.HatDurakGuzergah.GetDurak_XMLResponse retVal = ((IETT_GUI.HatDurakGuzergah.WebService1Soap)(this)).GetDurak_XML(inValue);
            return retVal.Body.GetDurak_XMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IETT_GUI.HatDurakGuzergah.GetDurak_XMLResponse> IETT_GUI.HatDurakGuzergah.WebService1Soap.GetDurak_XMLAsync(IETT_GUI.HatDurakGuzergah.GetDurak_XMLRequest request) {
            return base.Channel.GetDurak_XMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<IETT_GUI.HatDurakGuzergah.GetDurak_XMLResponse> GetDurak_XMLAsync(string DurakKodu) {
            IETT_GUI.HatDurakGuzergah.GetDurak_XMLRequest inValue = new IETT_GUI.HatDurakGuzergah.GetDurak_XMLRequest();
            inValue.Body = new IETT_GUI.HatDurakGuzergah.GetDurak_XMLRequestBody();
            inValue.Body.DurakKodu = DurakKodu;
            return ((IETT_GUI.HatDurakGuzergah.WebService1Soap)(this)).GetDurak_XMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IETT_GUI.HatDurakGuzergah.GetDurak_jsonResponse IETT_GUI.HatDurakGuzergah.WebService1Soap.GetDurak_json(IETT_GUI.HatDurakGuzergah.GetDurak_jsonRequest request) {
            return base.Channel.GetDurak_json(request);
        }
        
        public string GetDurak_json(string DurakKodu) {
            IETT_GUI.HatDurakGuzergah.GetDurak_jsonRequest inValue = new IETT_GUI.HatDurakGuzergah.GetDurak_jsonRequest();
            inValue.Body = new IETT_GUI.HatDurakGuzergah.GetDurak_jsonRequestBody();
            inValue.Body.DurakKodu = DurakKodu;
            IETT_GUI.HatDurakGuzergah.GetDurak_jsonResponse retVal = ((IETT_GUI.HatDurakGuzergah.WebService1Soap)(this)).GetDurak_json(inValue);
            return retVal.Body.GetDurak_jsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IETT_GUI.HatDurakGuzergah.GetDurak_jsonResponse> IETT_GUI.HatDurakGuzergah.WebService1Soap.GetDurak_jsonAsync(IETT_GUI.HatDurakGuzergah.GetDurak_jsonRequest request) {
            return base.Channel.GetDurak_jsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<IETT_GUI.HatDurakGuzergah.GetDurak_jsonResponse> GetDurak_jsonAsync(string DurakKodu) {
            IETT_GUI.HatDurakGuzergah.GetDurak_jsonRequest inValue = new IETT_GUI.HatDurakGuzergah.GetDurak_jsonRequest();
            inValue.Body = new IETT_GUI.HatDurakGuzergah.GetDurak_jsonRequestBody();
            inValue.Body.DurakKodu = DurakKodu;
            return ((IETT_GUI.HatDurakGuzergah.WebService1Soap)(this)).GetDurak_jsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IETT_GUI.HatDurakGuzergah.GetGaraj_XMLResponse IETT_GUI.HatDurakGuzergah.WebService1Soap.GetGaraj_XML(IETT_GUI.HatDurakGuzergah.GetGaraj_XMLRequest request) {
            return base.Channel.GetGaraj_XML(request);
        }
        
        public System.Xml.Linq.XElement GetGaraj_XML() {
            IETT_GUI.HatDurakGuzergah.GetGaraj_XMLRequest inValue = new IETT_GUI.HatDurakGuzergah.GetGaraj_XMLRequest();
            inValue.Body = new IETT_GUI.HatDurakGuzergah.GetGaraj_XMLRequestBody();
            IETT_GUI.HatDurakGuzergah.GetGaraj_XMLResponse retVal = ((IETT_GUI.HatDurakGuzergah.WebService1Soap)(this)).GetGaraj_XML(inValue);
            return retVal.Body.GetGaraj_XMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IETT_GUI.HatDurakGuzergah.GetGaraj_XMLResponse> IETT_GUI.HatDurakGuzergah.WebService1Soap.GetGaraj_XMLAsync(IETT_GUI.HatDurakGuzergah.GetGaraj_XMLRequest request) {
            return base.Channel.GetGaraj_XMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<IETT_GUI.HatDurakGuzergah.GetGaraj_XMLResponse> GetGaraj_XMLAsync() {
            IETT_GUI.HatDurakGuzergah.GetGaraj_XMLRequest inValue = new IETT_GUI.HatDurakGuzergah.GetGaraj_XMLRequest();
            inValue.Body = new IETT_GUI.HatDurakGuzergah.GetGaraj_XMLRequestBody();
            return ((IETT_GUI.HatDurakGuzergah.WebService1Soap)(this)).GetGaraj_XMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IETT_GUI.HatDurakGuzergah.GetGaraj_jsonResponse IETT_GUI.HatDurakGuzergah.WebService1Soap.GetGaraj_json(IETT_GUI.HatDurakGuzergah.GetGaraj_jsonRequest request) {
            return base.Channel.GetGaraj_json(request);
        }
        
        public string GetGaraj_json() {
            IETT_GUI.HatDurakGuzergah.GetGaraj_jsonRequest inValue = new IETT_GUI.HatDurakGuzergah.GetGaraj_jsonRequest();
            inValue.Body = new IETT_GUI.HatDurakGuzergah.GetGaraj_jsonRequestBody();
            IETT_GUI.HatDurakGuzergah.GetGaraj_jsonResponse retVal = ((IETT_GUI.HatDurakGuzergah.WebService1Soap)(this)).GetGaraj_json(inValue);
            return retVal.Body.GetGaraj_jsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IETT_GUI.HatDurakGuzergah.GetGaraj_jsonResponse> IETT_GUI.HatDurakGuzergah.WebService1Soap.GetGaraj_jsonAsync(IETT_GUI.HatDurakGuzergah.GetGaraj_jsonRequest request) {
            return base.Channel.GetGaraj_jsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<IETT_GUI.HatDurakGuzergah.GetGaraj_jsonResponse> GetGaraj_jsonAsync() {
            IETT_GUI.HatDurakGuzergah.GetGaraj_jsonRequest inValue = new IETT_GUI.HatDurakGuzergah.GetGaraj_jsonRequest();
            inValue.Body = new IETT_GUI.HatDurakGuzergah.GetGaraj_jsonRequestBody();
            return ((IETT_GUI.HatDurakGuzergah.WebService1Soap)(this)).GetGaraj_jsonAsync(inValue);
        }
    }
}
