//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IETT_GUI.Duyurular {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Duyurular.DuyurularSoap")]
    public interface DuyurularSoap {
        
        // CODEGEN: Generating message contract since element name GetDuyurular_XMLResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDuyurular_XML", ReplyAction="*")]
        IETT_GUI.Duyurular.GetDuyurular_XMLResponse GetDuyurular_XML(IETT_GUI.Duyurular.GetDuyurular_XMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDuyurular_XML", ReplyAction="*")]
        System.Threading.Tasks.Task<IETT_GUI.Duyurular.GetDuyurular_XMLResponse> GetDuyurular_XMLAsync(IETT_GUI.Duyurular.GetDuyurular_XMLRequest request);
        
        // CODEGEN: Generating message contract since element name GetDuyurular_jsonResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDuyurular_json", ReplyAction="*")]
        IETT_GUI.Duyurular.GetDuyurular_jsonResponse GetDuyurular_json(IETT_GUI.Duyurular.GetDuyurular_jsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDuyurular_json", ReplyAction="*")]
        System.Threading.Tasks.Task<IETT_GUI.Duyurular.GetDuyurular_jsonResponse> GetDuyurular_jsonAsync(IETT_GUI.Duyurular.GetDuyurular_jsonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDuyurular_XMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDuyurular_XML", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.Duyurular.GetDuyurular_XMLRequestBody Body;
        
        public GetDuyurular_XMLRequest() {
        }
        
        public GetDuyurular_XMLRequest(IETT_GUI.Duyurular.GetDuyurular_XMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDuyurular_XMLRequestBody {
        
        public GetDuyurular_XMLRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDuyurular_XMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDuyurular_XMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.Duyurular.GetDuyurular_XMLResponseBody Body;
        
        public GetDuyurular_XMLResponse() {
        }
        
        public GetDuyurular_XMLResponse(IETT_GUI.Duyurular.GetDuyurular_XMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDuyurular_XMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetDuyurular_XMLResult;
        
        public GetDuyurular_XMLResponseBody() {
        }
        
        public GetDuyurular_XMLResponseBody(System.Xml.Linq.XElement GetDuyurular_XMLResult) {
            this.GetDuyurular_XMLResult = GetDuyurular_XMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDuyurular_jsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDuyurular_json", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.Duyurular.GetDuyurular_jsonRequestBody Body;
        
        public GetDuyurular_jsonRequest() {
        }
        
        public GetDuyurular_jsonRequest(IETT_GUI.Duyurular.GetDuyurular_jsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDuyurular_jsonRequestBody {
        
        public GetDuyurular_jsonRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDuyurular_jsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDuyurular_jsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.Duyurular.GetDuyurular_jsonResponseBody Body;
        
        public GetDuyurular_jsonResponse() {
        }
        
        public GetDuyurular_jsonResponse(IETT_GUI.Duyurular.GetDuyurular_jsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDuyurular_jsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDuyurular_jsonResult;
        
        public GetDuyurular_jsonResponseBody() {
        }
        
        public GetDuyurular_jsonResponseBody(string GetDuyurular_jsonResult) {
            this.GetDuyurular_jsonResult = GetDuyurular_jsonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DuyurularSoapChannel : IETT_GUI.Duyurular.DuyurularSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DuyurularSoapClient : System.ServiceModel.ClientBase<IETT_GUI.Duyurular.DuyurularSoap>, IETT_GUI.Duyurular.DuyurularSoap {
        
        public DuyurularSoapClient() {
        }
        
        public DuyurularSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DuyurularSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DuyurularSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DuyurularSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IETT_GUI.Duyurular.GetDuyurular_XMLResponse IETT_GUI.Duyurular.DuyurularSoap.GetDuyurular_XML(IETT_GUI.Duyurular.GetDuyurular_XMLRequest request) {
            return base.Channel.GetDuyurular_XML(request);
        }
        
        public System.Xml.Linq.XElement GetDuyurular_XML() {
            IETT_GUI.Duyurular.GetDuyurular_XMLRequest inValue = new IETT_GUI.Duyurular.GetDuyurular_XMLRequest();
            inValue.Body = new IETT_GUI.Duyurular.GetDuyurular_XMLRequestBody();
            IETT_GUI.Duyurular.GetDuyurular_XMLResponse retVal = ((IETT_GUI.Duyurular.DuyurularSoap)(this)).GetDuyurular_XML(inValue);
            return retVal.Body.GetDuyurular_XMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IETT_GUI.Duyurular.GetDuyurular_XMLResponse> IETT_GUI.Duyurular.DuyurularSoap.GetDuyurular_XMLAsync(IETT_GUI.Duyurular.GetDuyurular_XMLRequest request) {
            return base.Channel.GetDuyurular_XMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<IETT_GUI.Duyurular.GetDuyurular_XMLResponse> GetDuyurular_XMLAsync() {
            IETT_GUI.Duyurular.GetDuyurular_XMLRequest inValue = new IETT_GUI.Duyurular.GetDuyurular_XMLRequest();
            inValue.Body = new IETT_GUI.Duyurular.GetDuyurular_XMLRequestBody();
            return ((IETT_GUI.Duyurular.DuyurularSoap)(this)).GetDuyurular_XMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IETT_GUI.Duyurular.GetDuyurular_jsonResponse IETT_GUI.Duyurular.DuyurularSoap.GetDuyurular_json(IETT_GUI.Duyurular.GetDuyurular_jsonRequest request) {
            return base.Channel.GetDuyurular_json(request);
        }
        
        public string GetDuyurular_json() {
            IETT_GUI.Duyurular.GetDuyurular_jsonRequest inValue = new IETT_GUI.Duyurular.GetDuyurular_jsonRequest();
            inValue.Body = new IETT_GUI.Duyurular.GetDuyurular_jsonRequestBody();
            IETT_GUI.Duyurular.GetDuyurular_jsonResponse retVal = ((IETT_GUI.Duyurular.DuyurularSoap)(this)).GetDuyurular_json(inValue);
            return retVal.Body.GetDuyurular_jsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IETT_GUI.Duyurular.GetDuyurular_jsonResponse> IETT_GUI.Duyurular.DuyurularSoap.GetDuyurular_jsonAsync(IETT_GUI.Duyurular.GetDuyurular_jsonRequest request) {
            return base.Channel.GetDuyurular_jsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<IETT_GUI.Duyurular.GetDuyurular_jsonResponse> GetDuyurular_jsonAsync() {
            IETT_GUI.Duyurular.GetDuyurular_jsonRequest inValue = new IETT_GUI.Duyurular.GetDuyurular_jsonRequest();
            inValue.Body = new IETT_GUI.Duyurular.GetDuyurular_jsonRequestBody();
            return ((IETT_GUI.Duyurular.DuyurularSoap)(this)).GetDuyurular_jsonAsync(inValue);
        }
    }
}
