//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IETT_GUI.IBB360 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBB360.ibb360Soap")]
    public interface ibb360Soap {
        
        // CODEGEN: Generating message contract since element name Tarih from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIettArsivGorev_XML", ReplyAction="*")]
        IETT_GUI.IBB360.GetIettArsivGorev_XMLResponse GetIettArsivGorev_XML(IETT_GUI.IBB360.GetIettArsivGorev_XMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIettArsivGorev_XML", ReplyAction="*")]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetIettArsivGorev_XMLResponse> GetIettArsivGorev_XMLAsync(IETT_GUI.IBB360.GetIettArsivGorev_XMLRequest request);
        
        // CODEGEN: Generating message contract since element name Tarih from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIettArsivGorev_json", ReplyAction="*")]
        IETT_GUI.IBB360.GetIettArsivGorev_jsonResponse GetIettArsivGorev_json(IETT_GUI.IBB360.GetIettArsivGorev_jsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIettArsivGorev_json", ReplyAction="*")]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetIettArsivGorev_jsonResponse> GetIettArsivGorev_jsonAsync(IETT_GUI.IBB360.GetIettArsivGorev_jsonRequest request);
        
        // CODEGEN: Generating message contract since element name Tarih from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetArsivGorev_Sas_IBB_XML", ReplyAction="*")]
        IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_XMLResponse GetArsivGorev_Sas_IBB_XML(IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_XMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetArsivGorev_Sas_IBB_XML", ReplyAction="*")]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_XMLResponse> GetArsivGorev_Sas_IBB_XMLAsync(IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_XMLRequest request);
        
        // CODEGEN: Generating message contract since element name Tarih from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetArsivGorev_Sas_IBB_json", ReplyAction="*")]
        IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_jsonResponse GetArsivGorev_Sas_IBB_json(IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_jsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetArsivGorev_Sas_IBB_json", ReplyAction="*")]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_jsonResponse> GetArsivGorev_Sas_IBB_jsonAsync(IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_jsonRequest request);
        
        // CODEGEN: Generating message contract since element name Tarih from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIBBZamanCizelgesi_XML", ReplyAction="*")]
        IETT_GUI.IBB360.GetIBBZamanCizelgesi_XMLResponse GetIBBZamanCizelgesi_XML(IETT_GUI.IBB360.GetIBBZamanCizelgesi_XMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIBBZamanCizelgesi_XML", ReplyAction="*")]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetIBBZamanCizelgesi_XMLResponse> GetIBBZamanCizelgesi_XMLAsync(IETT_GUI.IBB360.GetIBBZamanCizelgesi_XMLRequest request);
        
        // CODEGEN: Generating message contract since element name Tarih from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIBBZamanCizelgesi_json", ReplyAction="*")]
        IETT_GUI.IBB360.GetIBBZamanCizelgesi_jsonResponse GetIBBZamanCizelgesi_json(IETT_GUI.IBB360.GetIBBZamanCizelgesi_jsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIBBZamanCizelgesi_json", ReplyAction="*")]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetIBBZamanCizelgesi_jsonResponse> GetIBBZamanCizelgesi_jsonAsync(IETT_GUI.IBB360.GetIBBZamanCizelgesi_jsonRequest request);
        
        // CODEGEN: Generating message contract since element name ilceAdi from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMahalleHat_XML", ReplyAction="*")]
        IETT_GUI.IBB360.GetMahalleHat_XMLResponse GetMahalleHat_XML(IETT_GUI.IBB360.GetMahalleHat_XMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMahalleHat_XML", ReplyAction="*")]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetMahalleHat_XMLResponse> GetMahalleHat_XMLAsync(IETT_GUI.IBB360.GetMahalleHat_XMLRequest request);
        
        // CODEGEN: Generating message contract since element name ilceAdi from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMahalleHat_json", ReplyAction="*")]
        IETT_GUI.IBB360.GetMahalleHat_jsonResponse GetMahalleHat_json(IETT_GUI.IBB360.GetMahalleHat_jsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMahalleHat_json", ReplyAction="*")]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetMahalleHat_jsonResponse> GetMahalleHat_jsonAsync(IETT_GUI.IBB360.GetMahalleHat_jsonRequest request);
        
        // CODEGEN: Generating message contract since element name GuzergahKodu from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGuzergahLineString_XML", ReplyAction="*")]
        IETT_GUI.IBB360.GetGuzergahLineString_XMLResponse GetGuzergahLineString_XML(IETT_GUI.IBB360.GetGuzergahLineString_XMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGuzergahLineString_XML", ReplyAction="*")]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetGuzergahLineString_XMLResponse> GetGuzergahLineString_XMLAsync(IETT_GUI.IBB360.GetGuzergahLineString_XMLRequest request);
        
        // CODEGEN: Generating message contract since element name GuzergahKodu from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGuzergahLineString_json", ReplyAction="*")]
        IETT_GUI.IBB360.GetGuzergahLineString_jsonResponse GetGuzergahLineString_json(IETT_GUI.IBB360.GetGuzergahLineString_jsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGuzergahLineString_json", ReplyAction="*")]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetGuzergahLineString_jsonResponse> GetGuzergahLineString_jsonAsync(IETT_GUI.IBB360.GetGuzergahLineString_jsonRequest request);
        
        // CODEGEN: Generating message contract since element name GetHatBazliYolcuAdet_XMLResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHatBazliYolcuAdet_XML", ReplyAction="*")]
        IETT_GUI.IBB360.GetHatBazliYolcuAdet_XMLResponse GetHatBazliYolcuAdet_XML(IETT_GUI.IBB360.GetHatBazliYolcuAdet_XMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHatBazliYolcuAdet_XML", ReplyAction="*")]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetHatBazliYolcuAdet_XMLResponse> GetHatBazliYolcuAdet_XMLAsync(IETT_GUI.IBB360.GetHatBazliYolcuAdet_XMLRequest request);
        
        // CODEGEN: Generating message contract since element name GetHatBazliYolcuAdet_jsonResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHatBazliYolcuAdet_json", ReplyAction="*")]
        IETT_GUI.IBB360.GetHatBazliYolcuAdet_jsonResponse GetHatBazliYolcuAdet_json(IETT_GUI.IBB360.GetHatBazliYolcuAdet_jsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHatBazliYolcuAdet_json", ReplyAction="*")]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetHatBazliYolcuAdet_jsonResponse> GetHatBazliYolcuAdet_jsonAsync(IETT_GUI.IBB360.GetHatBazliYolcuAdet_jsonRequest request);
        
        // CODEGEN: Generating message contract since element name Tarih from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIettYolculukHat_XML", ReplyAction="*")]
        IETT_GUI.IBB360.GetIettYolculukHat_XMLResponse GetIettYolculukHat_XML(IETT_GUI.IBB360.GetIettYolculukHat_XMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIettYolculukHat_XML", ReplyAction="*")]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetIettYolculukHat_XMLResponse> GetIettYolculukHat_XMLAsync(IETT_GUI.IBB360.GetIettYolculukHat_XMLRequest request);
        
        // CODEGEN: Generating message contract since element name Tarih from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIettYolculukHat_json", ReplyAction="*")]
        IETT_GUI.IBB360.GetIettYolculukHat_jsonResponse GetIettYolculukHat_json(IETT_GUI.IBB360.GetIettYolculukHat_jsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIettYolculukHat_json", ReplyAction="*")]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetIettYolculukHat_jsonResponse> GetIettYolculukHat_jsonAsync(IETT_GUI.IBB360.GetIettYolculukHat_jsonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIettArsivGorev_XMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIettArsivGorev_XML", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetIettArsivGorev_XMLRequestBody Body;
        
        public GetIettArsivGorev_XMLRequest() {
        }
        
        public GetIettArsivGorev_XMLRequest(IETT_GUI.IBB360.GetIettArsivGorev_XMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIettArsivGorev_XMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Tarih;
        
        public GetIettArsivGorev_XMLRequestBody() {
        }
        
        public GetIettArsivGorev_XMLRequestBody(string Tarih) {
            this.Tarih = Tarih;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIettArsivGorev_XMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIettArsivGorev_XMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetIettArsivGorev_XMLResponseBody Body;
        
        public GetIettArsivGorev_XMLResponse() {
        }
        
        public GetIettArsivGorev_XMLResponse(IETT_GUI.IBB360.GetIettArsivGorev_XMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIettArsivGorev_XMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetIettArsivGorev_XMLResult;
        
        public GetIettArsivGorev_XMLResponseBody() {
        }
        
        public GetIettArsivGorev_XMLResponseBody(System.Xml.Linq.XElement GetIettArsivGorev_XMLResult) {
            this.GetIettArsivGorev_XMLResult = GetIettArsivGorev_XMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIettArsivGorev_jsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIettArsivGorev_json", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetIettArsivGorev_jsonRequestBody Body;
        
        public GetIettArsivGorev_jsonRequest() {
        }
        
        public GetIettArsivGorev_jsonRequest(IETT_GUI.IBB360.GetIettArsivGorev_jsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIettArsivGorev_jsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Tarih;
        
        public GetIettArsivGorev_jsonRequestBody() {
        }
        
        public GetIettArsivGorev_jsonRequestBody(string Tarih) {
            this.Tarih = Tarih;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIettArsivGorev_jsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIettArsivGorev_jsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetIettArsivGorev_jsonResponseBody Body;
        
        public GetIettArsivGorev_jsonResponse() {
        }
        
        public GetIettArsivGorev_jsonResponse(IETT_GUI.IBB360.GetIettArsivGorev_jsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIettArsivGorev_jsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetIettArsivGorev_jsonResult;
        
        public GetIettArsivGorev_jsonResponseBody() {
        }
        
        public GetIettArsivGorev_jsonResponseBody(string GetIettArsivGorev_jsonResult) {
            this.GetIettArsivGorev_jsonResult = GetIettArsivGorev_jsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetArsivGorev_Sas_IBB_XMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetArsivGorev_Sas_IBB_XML", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_XMLRequestBody Body;
        
        public GetArsivGorev_Sas_IBB_XMLRequest() {
        }
        
        public GetArsivGorev_Sas_IBB_XMLRequest(IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_XMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetArsivGorev_Sas_IBB_XMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Tarih;
        
        public GetArsivGorev_Sas_IBB_XMLRequestBody() {
        }
        
        public GetArsivGorev_Sas_IBB_XMLRequestBody(string Tarih) {
            this.Tarih = Tarih;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetArsivGorev_Sas_IBB_XMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetArsivGorev_Sas_IBB_XMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_XMLResponseBody Body;
        
        public GetArsivGorev_Sas_IBB_XMLResponse() {
        }
        
        public GetArsivGorev_Sas_IBB_XMLResponse(IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_XMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetArsivGorev_Sas_IBB_XMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetArsivGorev_Sas_IBB_XMLResult;
        
        public GetArsivGorev_Sas_IBB_XMLResponseBody() {
        }
        
        public GetArsivGorev_Sas_IBB_XMLResponseBody(System.Xml.Linq.XElement GetArsivGorev_Sas_IBB_XMLResult) {
            this.GetArsivGorev_Sas_IBB_XMLResult = GetArsivGorev_Sas_IBB_XMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetArsivGorev_Sas_IBB_jsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetArsivGorev_Sas_IBB_json", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_jsonRequestBody Body;
        
        public GetArsivGorev_Sas_IBB_jsonRequest() {
        }
        
        public GetArsivGorev_Sas_IBB_jsonRequest(IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_jsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetArsivGorev_Sas_IBB_jsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Tarih;
        
        public GetArsivGorev_Sas_IBB_jsonRequestBody() {
        }
        
        public GetArsivGorev_Sas_IBB_jsonRequestBody(string Tarih) {
            this.Tarih = Tarih;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetArsivGorev_Sas_IBB_jsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetArsivGorev_Sas_IBB_jsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_jsonResponseBody Body;
        
        public GetArsivGorev_Sas_IBB_jsonResponse() {
        }
        
        public GetArsivGorev_Sas_IBB_jsonResponse(IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_jsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetArsivGorev_Sas_IBB_jsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetArsivGorev_Sas_IBB_jsonResult;
        
        public GetArsivGorev_Sas_IBB_jsonResponseBody() {
        }
        
        public GetArsivGorev_Sas_IBB_jsonResponseBody(string GetArsivGorev_Sas_IBB_jsonResult) {
            this.GetArsivGorev_Sas_IBB_jsonResult = GetArsivGorev_Sas_IBB_jsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIBBZamanCizelgesi_XMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIBBZamanCizelgesi_XML", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetIBBZamanCizelgesi_XMLRequestBody Body;
        
        public GetIBBZamanCizelgesi_XMLRequest() {
        }
        
        public GetIBBZamanCizelgesi_XMLRequest(IETT_GUI.IBB360.GetIBBZamanCizelgesi_XMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIBBZamanCizelgesi_XMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Tarih;
        
        public GetIBBZamanCizelgesi_XMLRequestBody() {
        }
        
        public GetIBBZamanCizelgesi_XMLRequestBody(string Tarih) {
            this.Tarih = Tarih;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIBBZamanCizelgesi_XMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIBBZamanCizelgesi_XMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetIBBZamanCizelgesi_XMLResponseBody Body;
        
        public GetIBBZamanCizelgesi_XMLResponse() {
        }
        
        public GetIBBZamanCizelgesi_XMLResponse(IETT_GUI.IBB360.GetIBBZamanCizelgesi_XMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIBBZamanCizelgesi_XMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetIBBZamanCizelgesi_XMLResult;
        
        public GetIBBZamanCizelgesi_XMLResponseBody() {
        }
        
        public GetIBBZamanCizelgesi_XMLResponseBody(System.Xml.Linq.XElement GetIBBZamanCizelgesi_XMLResult) {
            this.GetIBBZamanCizelgesi_XMLResult = GetIBBZamanCizelgesi_XMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIBBZamanCizelgesi_jsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIBBZamanCizelgesi_json", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetIBBZamanCizelgesi_jsonRequestBody Body;
        
        public GetIBBZamanCizelgesi_jsonRequest() {
        }
        
        public GetIBBZamanCizelgesi_jsonRequest(IETT_GUI.IBB360.GetIBBZamanCizelgesi_jsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIBBZamanCizelgesi_jsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Tarih;
        
        public GetIBBZamanCizelgesi_jsonRequestBody() {
        }
        
        public GetIBBZamanCizelgesi_jsonRequestBody(string Tarih) {
            this.Tarih = Tarih;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIBBZamanCizelgesi_jsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIBBZamanCizelgesi_jsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetIBBZamanCizelgesi_jsonResponseBody Body;
        
        public GetIBBZamanCizelgesi_jsonResponse() {
        }
        
        public GetIBBZamanCizelgesi_jsonResponse(IETT_GUI.IBB360.GetIBBZamanCizelgesi_jsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIBBZamanCizelgesi_jsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetIBBZamanCizelgesi_jsonResult;
        
        public GetIBBZamanCizelgesi_jsonResponseBody() {
        }
        
        public GetIBBZamanCizelgesi_jsonResponseBody(string GetIBBZamanCizelgesi_jsonResult) {
            this.GetIBBZamanCizelgesi_jsonResult = GetIBBZamanCizelgesi_jsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMahalleHat_XMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMahalleHat_XML", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetMahalleHat_XMLRequestBody Body;
        
        public GetMahalleHat_XMLRequest() {
        }
        
        public GetMahalleHat_XMLRequest(IETT_GUI.IBB360.GetMahalleHat_XMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMahalleHat_XMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ilceAdi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mahalle;
        
        public GetMahalleHat_XMLRequestBody() {
        }
        
        public GetMahalleHat_XMLRequestBody(string ilceAdi, string Mahalle) {
            this.ilceAdi = ilceAdi;
            this.Mahalle = Mahalle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMahalleHat_XMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMahalleHat_XMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetMahalleHat_XMLResponseBody Body;
        
        public GetMahalleHat_XMLResponse() {
        }
        
        public GetMahalleHat_XMLResponse(IETT_GUI.IBB360.GetMahalleHat_XMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMahalleHat_XMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetMahalleHat_XMLResult;
        
        public GetMahalleHat_XMLResponseBody() {
        }
        
        public GetMahalleHat_XMLResponseBody(System.Xml.Linq.XElement GetMahalleHat_XMLResult) {
            this.GetMahalleHat_XMLResult = GetMahalleHat_XMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMahalleHat_jsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMahalleHat_json", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetMahalleHat_jsonRequestBody Body;
        
        public GetMahalleHat_jsonRequest() {
        }
        
        public GetMahalleHat_jsonRequest(IETT_GUI.IBB360.GetMahalleHat_jsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMahalleHat_jsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ilceAdi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mahalle;
        
        public GetMahalleHat_jsonRequestBody() {
        }
        
        public GetMahalleHat_jsonRequestBody(string ilceAdi, string Mahalle) {
            this.ilceAdi = ilceAdi;
            this.Mahalle = Mahalle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMahalleHat_jsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMahalleHat_jsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetMahalleHat_jsonResponseBody Body;
        
        public GetMahalleHat_jsonResponse() {
        }
        
        public GetMahalleHat_jsonResponse(IETT_GUI.IBB360.GetMahalleHat_jsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMahalleHat_jsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMahalleHat_jsonResult;
        
        public GetMahalleHat_jsonResponseBody() {
        }
        
        public GetMahalleHat_jsonResponseBody(string GetMahalleHat_jsonResult) {
            this.GetMahalleHat_jsonResult = GetMahalleHat_jsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGuzergahLineString_XMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGuzergahLineString_XML", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetGuzergahLineString_XMLRequestBody Body;
        
        public GetGuzergahLineString_XMLRequest() {
        }
        
        public GetGuzergahLineString_XMLRequest(IETT_GUI.IBB360.GetGuzergahLineString_XMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGuzergahLineString_XMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GuzergahKodu;
        
        public GetGuzergahLineString_XMLRequestBody() {
        }
        
        public GetGuzergahLineString_XMLRequestBody(string GuzergahKodu) {
            this.GuzergahKodu = GuzergahKodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGuzergahLineString_XMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGuzergahLineString_XMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetGuzergahLineString_XMLResponseBody Body;
        
        public GetGuzergahLineString_XMLResponse() {
        }
        
        public GetGuzergahLineString_XMLResponse(IETT_GUI.IBB360.GetGuzergahLineString_XMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGuzergahLineString_XMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetGuzergahLineString_XMLResult;
        
        public GetGuzergahLineString_XMLResponseBody() {
        }
        
        public GetGuzergahLineString_XMLResponseBody(System.Xml.Linq.XElement GetGuzergahLineString_XMLResult) {
            this.GetGuzergahLineString_XMLResult = GetGuzergahLineString_XMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGuzergahLineString_jsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGuzergahLineString_json", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetGuzergahLineString_jsonRequestBody Body;
        
        public GetGuzergahLineString_jsonRequest() {
        }
        
        public GetGuzergahLineString_jsonRequest(IETT_GUI.IBB360.GetGuzergahLineString_jsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGuzergahLineString_jsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GuzergahKodu;
        
        public GetGuzergahLineString_jsonRequestBody() {
        }
        
        public GetGuzergahLineString_jsonRequestBody(string GuzergahKodu) {
            this.GuzergahKodu = GuzergahKodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGuzergahLineString_jsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGuzergahLineString_jsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetGuzergahLineString_jsonResponseBody Body;
        
        public GetGuzergahLineString_jsonResponse() {
        }
        
        public GetGuzergahLineString_jsonResponse(IETT_GUI.IBB360.GetGuzergahLineString_jsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGuzergahLineString_jsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGuzergahLineString_jsonResult;
        
        public GetGuzergahLineString_jsonResponseBody() {
        }
        
        public GetGuzergahLineString_jsonResponseBody(string GetGuzergahLineString_jsonResult) {
            this.GetGuzergahLineString_jsonResult = GetGuzergahLineString_jsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHatBazliYolcuAdet_XMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHatBazliYolcuAdet_XML", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetHatBazliYolcuAdet_XMLRequestBody Body;
        
        public GetHatBazliYolcuAdet_XMLRequest() {
        }
        
        public GetHatBazliYolcuAdet_XMLRequest(IETT_GUI.IBB360.GetHatBazliYolcuAdet_XMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetHatBazliYolcuAdet_XMLRequestBody {
        
        public GetHatBazliYolcuAdet_XMLRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHatBazliYolcuAdet_XMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHatBazliYolcuAdet_XMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetHatBazliYolcuAdet_XMLResponseBody Body;
        
        public GetHatBazliYolcuAdet_XMLResponse() {
        }
        
        public GetHatBazliYolcuAdet_XMLResponse(IETT_GUI.IBB360.GetHatBazliYolcuAdet_XMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHatBazliYolcuAdet_XMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetHatBazliYolcuAdet_XMLResult;
        
        public GetHatBazliYolcuAdet_XMLResponseBody() {
        }
        
        public GetHatBazliYolcuAdet_XMLResponseBody(System.Xml.Linq.XElement GetHatBazliYolcuAdet_XMLResult) {
            this.GetHatBazliYolcuAdet_XMLResult = GetHatBazliYolcuAdet_XMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHatBazliYolcuAdet_jsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHatBazliYolcuAdet_json", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetHatBazliYolcuAdet_jsonRequestBody Body;
        
        public GetHatBazliYolcuAdet_jsonRequest() {
        }
        
        public GetHatBazliYolcuAdet_jsonRequest(IETT_GUI.IBB360.GetHatBazliYolcuAdet_jsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetHatBazliYolcuAdet_jsonRequestBody {
        
        public GetHatBazliYolcuAdet_jsonRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHatBazliYolcuAdet_jsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHatBazliYolcuAdet_jsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetHatBazliYolcuAdet_jsonResponseBody Body;
        
        public GetHatBazliYolcuAdet_jsonResponse() {
        }
        
        public GetHatBazliYolcuAdet_jsonResponse(IETT_GUI.IBB360.GetHatBazliYolcuAdet_jsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHatBazliYolcuAdet_jsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetHatBazliYolcuAdet_jsonResult;
        
        public GetHatBazliYolcuAdet_jsonResponseBody() {
        }
        
        public GetHatBazliYolcuAdet_jsonResponseBody(string GetHatBazliYolcuAdet_jsonResult) {
            this.GetHatBazliYolcuAdet_jsonResult = GetHatBazliYolcuAdet_jsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIettYolculukHat_XMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIettYolculukHat_XML", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetIettYolculukHat_XMLRequestBody Body;
        
        public GetIettYolculukHat_XMLRequest() {
        }
        
        public GetIettYolculukHat_XMLRequest(IETT_GUI.IBB360.GetIettYolculukHat_XMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIettYolculukHat_XMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Tarih;
        
        public GetIettYolculukHat_XMLRequestBody() {
        }
        
        public GetIettYolculukHat_XMLRequestBody(string Tarih) {
            this.Tarih = Tarih;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIettYolculukHat_XMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIettYolculukHat_XMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetIettYolculukHat_XMLResponseBody Body;
        
        public GetIettYolculukHat_XMLResponse() {
        }
        
        public GetIettYolculukHat_XMLResponse(IETT_GUI.IBB360.GetIettYolculukHat_XMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIettYolculukHat_XMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetIettYolculukHat_XMLResult;
        
        public GetIettYolculukHat_XMLResponseBody() {
        }
        
        public GetIettYolculukHat_XMLResponseBody(System.Xml.Linq.XElement GetIettYolculukHat_XMLResult) {
            this.GetIettYolculukHat_XMLResult = GetIettYolculukHat_XMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIettYolculukHat_jsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIettYolculukHat_json", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetIettYolculukHat_jsonRequestBody Body;
        
        public GetIettYolculukHat_jsonRequest() {
        }
        
        public GetIettYolculukHat_jsonRequest(IETT_GUI.IBB360.GetIettYolculukHat_jsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIettYolculukHat_jsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Tarih;
        
        public GetIettYolculukHat_jsonRequestBody() {
        }
        
        public GetIettYolculukHat_jsonRequestBody(string Tarih) {
            this.Tarih = Tarih;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIettYolculukHat_jsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIettYolculukHat_jsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public IETT_GUI.IBB360.GetIettYolculukHat_jsonResponseBody Body;
        
        public GetIettYolculukHat_jsonResponse() {
        }
        
        public GetIettYolculukHat_jsonResponse(IETT_GUI.IBB360.GetIettYolculukHat_jsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIettYolculukHat_jsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetIettYolculukHat_jsonResult;
        
        public GetIettYolculukHat_jsonResponseBody() {
        }
        
        public GetIettYolculukHat_jsonResponseBody(string GetIettYolculukHat_jsonResult) {
            this.GetIettYolculukHat_jsonResult = GetIettYolculukHat_jsonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ibb360SoapChannel : IETT_GUI.IBB360.ibb360Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ibb360SoapClient : System.ServiceModel.ClientBase<IETT_GUI.IBB360.ibb360Soap>, IETT_GUI.IBB360.ibb360Soap {
        
        public ibb360SoapClient() {
        }
        
        public ibb360SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ibb360SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ibb360SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ibb360SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IETT_GUI.IBB360.GetIettArsivGorev_XMLResponse IETT_GUI.IBB360.ibb360Soap.GetIettArsivGorev_XML(IETT_GUI.IBB360.GetIettArsivGorev_XMLRequest request) {
            return base.Channel.GetIettArsivGorev_XML(request);
        }
        
        public System.Xml.Linq.XElement GetIettArsivGorev_XML(string Tarih) {
            IETT_GUI.IBB360.GetIettArsivGorev_XMLRequest inValue = new IETT_GUI.IBB360.GetIettArsivGorev_XMLRequest();
            inValue.Body = new IETT_GUI.IBB360.GetIettArsivGorev_XMLRequestBody();
            inValue.Body.Tarih = Tarih;
            IETT_GUI.IBB360.GetIettArsivGorev_XMLResponse retVal = ((IETT_GUI.IBB360.ibb360Soap)(this)).GetIettArsivGorev_XML(inValue);
            return retVal.Body.GetIettArsivGorev_XMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetIettArsivGorev_XMLResponse> IETT_GUI.IBB360.ibb360Soap.GetIettArsivGorev_XMLAsync(IETT_GUI.IBB360.GetIettArsivGorev_XMLRequest request) {
            return base.Channel.GetIettArsivGorev_XMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<IETT_GUI.IBB360.GetIettArsivGorev_XMLResponse> GetIettArsivGorev_XMLAsync(string Tarih) {
            IETT_GUI.IBB360.GetIettArsivGorev_XMLRequest inValue = new IETT_GUI.IBB360.GetIettArsivGorev_XMLRequest();
            inValue.Body = new IETT_GUI.IBB360.GetIettArsivGorev_XMLRequestBody();
            inValue.Body.Tarih = Tarih;
            return ((IETT_GUI.IBB360.ibb360Soap)(this)).GetIettArsivGorev_XMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IETT_GUI.IBB360.GetIettArsivGorev_jsonResponse IETT_GUI.IBB360.ibb360Soap.GetIettArsivGorev_json(IETT_GUI.IBB360.GetIettArsivGorev_jsonRequest request) {
            return base.Channel.GetIettArsivGorev_json(request);
        }
        
        public string GetIettArsivGorev_json(string Tarih) {
            IETT_GUI.IBB360.GetIettArsivGorev_jsonRequest inValue = new IETT_GUI.IBB360.GetIettArsivGorev_jsonRequest();
            inValue.Body = new IETT_GUI.IBB360.GetIettArsivGorev_jsonRequestBody();
            inValue.Body.Tarih = Tarih;
            IETT_GUI.IBB360.GetIettArsivGorev_jsonResponse retVal = ((IETT_GUI.IBB360.ibb360Soap)(this)).GetIettArsivGorev_json(inValue);
            return retVal.Body.GetIettArsivGorev_jsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetIettArsivGorev_jsonResponse> IETT_GUI.IBB360.ibb360Soap.GetIettArsivGorev_jsonAsync(IETT_GUI.IBB360.GetIettArsivGorev_jsonRequest request) {
            return base.Channel.GetIettArsivGorev_jsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<IETT_GUI.IBB360.GetIettArsivGorev_jsonResponse> GetIettArsivGorev_jsonAsync(string Tarih) {
            IETT_GUI.IBB360.GetIettArsivGorev_jsonRequest inValue = new IETT_GUI.IBB360.GetIettArsivGorev_jsonRequest();
            inValue.Body = new IETT_GUI.IBB360.GetIettArsivGorev_jsonRequestBody();
            inValue.Body.Tarih = Tarih;
            return ((IETT_GUI.IBB360.ibb360Soap)(this)).GetIettArsivGorev_jsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_XMLResponse IETT_GUI.IBB360.ibb360Soap.GetArsivGorev_Sas_IBB_XML(IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_XMLRequest request) {
            return base.Channel.GetArsivGorev_Sas_IBB_XML(request);
        }
        
        public System.Xml.Linq.XElement GetArsivGorev_Sas_IBB_XML(string Tarih) {
            IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_XMLRequest inValue = new IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_XMLRequest();
            inValue.Body = new IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_XMLRequestBody();
            inValue.Body.Tarih = Tarih;
            IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_XMLResponse retVal = ((IETT_GUI.IBB360.ibb360Soap)(this)).GetArsivGorev_Sas_IBB_XML(inValue);
            return retVal.Body.GetArsivGorev_Sas_IBB_XMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_XMLResponse> IETT_GUI.IBB360.ibb360Soap.GetArsivGorev_Sas_IBB_XMLAsync(IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_XMLRequest request) {
            return base.Channel.GetArsivGorev_Sas_IBB_XMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_XMLResponse> GetArsivGorev_Sas_IBB_XMLAsync(string Tarih) {
            IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_XMLRequest inValue = new IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_XMLRequest();
            inValue.Body = new IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_XMLRequestBody();
            inValue.Body.Tarih = Tarih;
            return ((IETT_GUI.IBB360.ibb360Soap)(this)).GetArsivGorev_Sas_IBB_XMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_jsonResponse IETT_GUI.IBB360.ibb360Soap.GetArsivGorev_Sas_IBB_json(IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_jsonRequest request) {
            return base.Channel.GetArsivGorev_Sas_IBB_json(request);
        }
        
        public string GetArsivGorev_Sas_IBB_json(string Tarih) {
            IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_jsonRequest inValue = new IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_jsonRequest();
            inValue.Body = new IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_jsonRequestBody();
            inValue.Body.Tarih = Tarih;
            IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_jsonResponse retVal = ((IETT_GUI.IBB360.ibb360Soap)(this)).GetArsivGorev_Sas_IBB_json(inValue);
            return retVal.Body.GetArsivGorev_Sas_IBB_jsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_jsonResponse> IETT_GUI.IBB360.ibb360Soap.GetArsivGorev_Sas_IBB_jsonAsync(IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_jsonRequest request) {
            return base.Channel.GetArsivGorev_Sas_IBB_jsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_jsonResponse> GetArsivGorev_Sas_IBB_jsonAsync(string Tarih) {
            IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_jsonRequest inValue = new IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_jsonRequest();
            inValue.Body = new IETT_GUI.IBB360.GetArsivGorev_Sas_IBB_jsonRequestBody();
            inValue.Body.Tarih = Tarih;
            return ((IETT_GUI.IBB360.ibb360Soap)(this)).GetArsivGorev_Sas_IBB_jsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IETT_GUI.IBB360.GetIBBZamanCizelgesi_XMLResponse IETT_GUI.IBB360.ibb360Soap.GetIBBZamanCizelgesi_XML(IETT_GUI.IBB360.GetIBBZamanCizelgesi_XMLRequest request) {
            return base.Channel.GetIBBZamanCizelgesi_XML(request);
        }
        
        public System.Xml.Linq.XElement GetIBBZamanCizelgesi_XML(string Tarih) {
            IETT_GUI.IBB360.GetIBBZamanCizelgesi_XMLRequest inValue = new IETT_GUI.IBB360.GetIBBZamanCizelgesi_XMLRequest();
            inValue.Body = new IETT_GUI.IBB360.GetIBBZamanCizelgesi_XMLRequestBody();
            inValue.Body.Tarih = Tarih;
            IETT_GUI.IBB360.GetIBBZamanCizelgesi_XMLResponse retVal = ((IETT_GUI.IBB360.ibb360Soap)(this)).GetIBBZamanCizelgesi_XML(inValue);
            return retVal.Body.GetIBBZamanCizelgesi_XMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetIBBZamanCizelgesi_XMLResponse> IETT_GUI.IBB360.ibb360Soap.GetIBBZamanCizelgesi_XMLAsync(IETT_GUI.IBB360.GetIBBZamanCizelgesi_XMLRequest request) {
            return base.Channel.GetIBBZamanCizelgesi_XMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<IETT_GUI.IBB360.GetIBBZamanCizelgesi_XMLResponse> GetIBBZamanCizelgesi_XMLAsync(string Tarih) {
            IETT_GUI.IBB360.GetIBBZamanCizelgesi_XMLRequest inValue = new IETT_GUI.IBB360.GetIBBZamanCizelgesi_XMLRequest();
            inValue.Body = new IETT_GUI.IBB360.GetIBBZamanCizelgesi_XMLRequestBody();
            inValue.Body.Tarih = Tarih;
            return ((IETT_GUI.IBB360.ibb360Soap)(this)).GetIBBZamanCizelgesi_XMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IETT_GUI.IBB360.GetIBBZamanCizelgesi_jsonResponse IETT_GUI.IBB360.ibb360Soap.GetIBBZamanCizelgesi_json(IETT_GUI.IBB360.GetIBBZamanCizelgesi_jsonRequest request) {
            return base.Channel.GetIBBZamanCizelgesi_json(request);
        }
        
        public string GetIBBZamanCizelgesi_json(string Tarih) {
            IETT_GUI.IBB360.GetIBBZamanCizelgesi_jsonRequest inValue = new IETT_GUI.IBB360.GetIBBZamanCizelgesi_jsonRequest();
            inValue.Body = new IETT_GUI.IBB360.GetIBBZamanCizelgesi_jsonRequestBody();
            inValue.Body.Tarih = Tarih;
            IETT_GUI.IBB360.GetIBBZamanCizelgesi_jsonResponse retVal = ((IETT_GUI.IBB360.ibb360Soap)(this)).GetIBBZamanCizelgesi_json(inValue);
            return retVal.Body.GetIBBZamanCizelgesi_jsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetIBBZamanCizelgesi_jsonResponse> IETT_GUI.IBB360.ibb360Soap.GetIBBZamanCizelgesi_jsonAsync(IETT_GUI.IBB360.GetIBBZamanCizelgesi_jsonRequest request) {
            return base.Channel.GetIBBZamanCizelgesi_jsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<IETT_GUI.IBB360.GetIBBZamanCizelgesi_jsonResponse> GetIBBZamanCizelgesi_jsonAsync(string Tarih) {
            IETT_GUI.IBB360.GetIBBZamanCizelgesi_jsonRequest inValue = new IETT_GUI.IBB360.GetIBBZamanCizelgesi_jsonRequest();
            inValue.Body = new IETT_GUI.IBB360.GetIBBZamanCizelgesi_jsonRequestBody();
            inValue.Body.Tarih = Tarih;
            return ((IETT_GUI.IBB360.ibb360Soap)(this)).GetIBBZamanCizelgesi_jsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IETT_GUI.IBB360.GetMahalleHat_XMLResponse IETT_GUI.IBB360.ibb360Soap.GetMahalleHat_XML(IETT_GUI.IBB360.GetMahalleHat_XMLRequest request) {
            return base.Channel.GetMahalleHat_XML(request);
        }
        
        public System.Xml.Linq.XElement GetMahalleHat_XML(string ilceAdi, string Mahalle) {
            IETT_GUI.IBB360.GetMahalleHat_XMLRequest inValue = new IETT_GUI.IBB360.GetMahalleHat_XMLRequest();
            inValue.Body = new IETT_GUI.IBB360.GetMahalleHat_XMLRequestBody();
            inValue.Body.ilceAdi = ilceAdi;
            inValue.Body.Mahalle = Mahalle;
            IETT_GUI.IBB360.GetMahalleHat_XMLResponse retVal = ((IETT_GUI.IBB360.ibb360Soap)(this)).GetMahalleHat_XML(inValue);
            return retVal.Body.GetMahalleHat_XMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetMahalleHat_XMLResponse> IETT_GUI.IBB360.ibb360Soap.GetMahalleHat_XMLAsync(IETT_GUI.IBB360.GetMahalleHat_XMLRequest request) {
            return base.Channel.GetMahalleHat_XMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<IETT_GUI.IBB360.GetMahalleHat_XMLResponse> GetMahalleHat_XMLAsync(string ilceAdi, string Mahalle) {
            IETT_GUI.IBB360.GetMahalleHat_XMLRequest inValue = new IETT_GUI.IBB360.GetMahalleHat_XMLRequest();
            inValue.Body = new IETT_GUI.IBB360.GetMahalleHat_XMLRequestBody();
            inValue.Body.ilceAdi = ilceAdi;
            inValue.Body.Mahalle = Mahalle;
            return ((IETT_GUI.IBB360.ibb360Soap)(this)).GetMahalleHat_XMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IETT_GUI.IBB360.GetMahalleHat_jsonResponse IETT_GUI.IBB360.ibb360Soap.GetMahalleHat_json(IETT_GUI.IBB360.GetMahalleHat_jsonRequest request) {
            return base.Channel.GetMahalleHat_json(request);
        }
        
        public string GetMahalleHat_json(string ilceAdi, string Mahalle) {
            IETT_GUI.IBB360.GetMahalleHat_jsonRequest inValue = new IETT_GUI.IBB360.GetMahalleHat_jsonRequest();
            inValue.Body = new IETT_GUI.IBB360.GetMahalleHat_jsonRequestBody();
            inValue.Body.ilceAdi = ilceAdi;
            inValue.Body.Mahalle = Mahalle;
            IETT_GUI.IBB360.GetMahalleHat_jsonResponse retVal = ((IETT_GUI.IBB360.ibb360Soap)(this)).GetMahalleHat_json(inValue);
            return retVal.Body.GetMahalleHat_jsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetMahalleHat_jsonResponse> IETT_GUI.IBB360.ibb360Soap.GetMahalleHat_jsonAsync(IETT_GUI.IBB360.GetMahalleHat_jsonRequest request) {
            return base.Channel.GetMahalleHat_jsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<IETT_GUI.IBB360.GetMahalleHat_jsonResponse> GetMahalleHat_jsonAsync(string ilceAdi, string Mahalle) {
            IETT_GUI.IBB360.GetMahalleHat_jsonRequest inValue = new IETT_GUI.IBB360.GetMahalleHat_jsonRequest();
            inValue.Body = new IETT_GUI.IBB360.GetMahalleHat_jsonRequestBody();
            inValue.Body.ilceAdi = ilceAdi;
            inValue.Body.Mahalle = Mahalle;
            return ((IETT_GUI.IBB360.ibb360Soap)(this)).GetMahalleHat_jsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IETT_GUI.IBB360.GetGuzergahLineString_XMLResponse IETT_GUI.IBB360.ibb360Soap.GetGuzergahLineString_XML(IETT_GUI.IBB360.GetGuzergahLineString_XMLRequest request) {
            return base.Channel.GetGuzergahLineString_XML(request);
        }
        
        public System.Xml.Linq.XElement GetGuzergahLineString_XML(string GuzergahKodu) {
            IETT_GUI.IBB360.GetGuzergahLineString_XMLRequest inValue = new IETT_GUI.IBB360.GetGuzergahLineString_XMLRequest();
            inValue.Body = new IETT_GUI.IBB360.GetGuzergahLineString_XMLRequestBody();
            inValue.Body.GuzergahKodu = GuzergahKodu;
            IETT_GUI.IBB360.GetGuzergahLineString_XMLResponse retVal = ((IETT_GUI.IBB360.ibb360Soap)(this)).GetGuzergahLineString_XML(inValue);
            return retVal.Body.GetGuzergahLineString_XMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetGuzergahLineString_XMLResponse> IETT_GUI.IBB360.ibb360Soap.GetGuzergahLineString_XMLAsync(IETT_GUI.IBB360.GetGuzergahLineString_XMLRequest request) {
            return base.Channel.GetGuzergahLineString_XMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<IETT_GUI.IBB360.GetGuzergahLineString_XMLResponse> GetGuzergahLineString_XMLAsync(string GuzergahKodu) {
            IETT_GUI.IBB360.GetGuzergahLineString_XMLRequest inValue = new IETT_GUI.IBB360.GetGuzergahLineString_XMLRequest();
            inValue.Body = new IETT_GUI.IBB360.GetGuzergahLineString_XMLRequestBody();
            inValue.Body.GuzergahKodu = GuzergahKodu;
            return ((IETT_GUI.IBB360.ibb360Soap)(this)).GetGuzergahLineString_XMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IETT_GUI.IBB360.GetGuzergahLineString_jsonResponse IETT_GUI.IBB360.ibb360Soap.GetGuzergahLineString_json(IETT_GUI.IBB360.GetGuzergahLineString_jsonRequest request) {
            return base.Channel.GetGuzergahLineString_json(request);
        }
        
        public string GetGuzergahLineString_json(string GuzergahKodu) {
            IETT_GUI.IBB360.GetGuzergahLineString_jsonRequest inValue = new IETT_GUI.IBB360.GetGuzergahLineString_jsonRequest();
            inValue.Body = new IETT_GUI.IBB360.GetGuzergahLineString_jsonRequestBody();
            inValue.Body.GuzergahKodu = GuzergahKodu;
            IETT_GUI.IBB360.GetGuzergahLineString_jsonResponse retVal = ((IETT_GUI.IBB360.ibb360Soap)(this)).GetGuzergahLineString_json(inValue);
            return retVal.Body.GetGuzergahLineString_jsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetGuzergahLineString_jsonResponse> IETT_GUI.IBB360.ibb360Soap.GetGuzergahLineString_jsonAsync(IETT_GUI.IBB360.GetGuzergahLineString_jsonRequest request) {
            return base.Channel.GetGuzergahLineString_jsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<IETT_GUI.IBB360.GetGuzergahLineString_jsonResponse> GetGuzergahLineString_jsonAsync(string GuzergahKodu) {
            IETT_GUI.IBB360.GetGuzergahLineString_jsonRequest inValue = new IETT_GUI.IBB360.GetGuzergahLineString_jsonRequest();
            inValue.Body = new IETT_GUI.IBB360.GetGuzergahLineString_jsonRequestBody();
            inValue.Body.GuzergahKodu = GuzergahKodu;
            return ((IETT_GUI.IBB360.ibb360Soap)(this)).GetGuzergahLineString_jsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IETT_GUI.IBB360.GetHatBazliYolcuAdet_XMLResponse IETT_GUI.IBB360.ibb360Soap.GetHatBazliYolcuAdet_XML(IETT_GUI.IBB360.GetHatBazliYolcuAdet_XMLRequest request) {
            return base.Channel.GetHatBazliYolcuAdet_XML(request);
        }
        
        public System.Xml.Linq.XElement GetHatBazliYolcuAdet_XML() {
            IETT_GUI.IBB360.GetHatBazliYolcuAdet_XMLRequest inValue = new IETT_GUI.IBB360.GetHatBazliYolcuAdet_XMLRequest();
            inValue.Body = new IETT_GUI.IBB360.GetHatBazliYolcuAdet_XMLRequestBody();
            IETT_GUI.IBB360.GetHatBazliYolcuAdet_XMLResponse retVal = ((IETT_GUI.IBB360.ibb360Soap)(this)).GetHatBazliYolcuAdet_XML(inValue);
            return retVal.Body.GetHatBazliYolcuAdet_XMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetHatBazliYolcuAdet_XMLResponse> IETT_GUI.IBB360.ibb360Soap.GetHatBazliYolcuAdet_XMLAsync(IETT_GUI.IBB360.GetHatBazliYolcuAdet_XMLRequest request) {
            return base.Channel.GetHatBazliYolcuAdet_XMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<IETT_GUI.IBB360.GetHatBazliYolcuAdet_XMLResponse> GetHatBazliYolcuAdet_XMLAsync() {
            IETT_GUI.IBB360.GetHatBazliYolcuAdet_XMLRequest inValue = new IETT_GUI.IBB360.GetHatBazliYolcuAdet_XMLRequest();
            inValue.Body = new IETT_GUI.IBB360.GetHatBazliYolcuAdet_XMLRequestBody();
            return ((IETT_GUI.IBB360.ibb360Soap)(this)).GetHatBazliYolcuAdet_XMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IETT_GUI.IBB360.GetHatBazliYolcuAdet_jsonResponse IETT_GUI.IBB360.ibb360Soap.GetHatBazliYolcuAdet_json(IETT_GUI.IBB360.GetHatBazliYolcuAdet_jsonRequest request) {
            return base.Channel.GetHatBazliYolcuAdet_json(request);
        }
        
        public string GetHatBazliYolcuAdet_json() {
            IETT_GUI.IBB360.GetHatBazliYolcuAdet_jsonRequest inValue = new IETT_GUI.IBB360.GetHatBazliYolcuAdet_jsonRequest();
            inValue.Body = new IETT_GUI.IBB360.GetHatBazliYolcuAdet_jsonRequestBody();
            IETT_GUI.IBB360.GetHatBazliYolcuAdet_jsonResponse retVal = ((IETT_GUI.IBB360.ibb360Soap)(this)).GetHatBazliYolcuAdet_json(inValue);
            return retVal.Body.GetHatBazliYolcuAdet_jsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetHatBazliYolcuAdet_jsonResponse> IETT_GUI.IBB360.ibb360Soap.GetHatBazliYolcuAdet_jsonAsync(IETT_GUI.IBB360.GetHatBazliYolcuAdet_jsonRequest request) {
            return base.Channel.GetHatBazliYolcuAdet_jsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<IETT_GUI.IBB360.GetHatBazliYolcuAdet_jsonResponse> GetHatBazliYolcuAdet_jsonAsync() {
            IETT_GUI.IBB360.GetHatBazliYolcuAdet_jsonRequest inValue = new IETT_GUI.IBB360.GetHatBazliYolcuAdet_jsonRequest();
            inValue.Body = new IETT_GUI.IBB360.GetHatBazliYolcuAdet_jsonRequestBody();
            return ((IETT_GUI.IBB360.ibb360Soap)(this)).GetHatBazliYolcuAdet_jsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IETT_GUI.IBB360.GetIettYolculukHat_XMLResponse IETT_GUI.IBB360.ibb360Soap.GetIettYolculukHat_XML(IETT_GUI.IBB360.GetIettYolculukHat_XMLRequest request) {
            return base.Channel.GetIettYolculukHat_XML(request);
        }
        
        public System.Xml.Linq.XElement GetIettYolculukHat_XML(string Tarih) {
            IETT_GUI.IBB360.GetIettYolculukHat_XMLRequest inValue = new IETT_GUI.IBB360.GetIettYolculukHat_XMLRequest();
            inValue.Body = new IETT_GUI.IBB360.GetIettYolculukHat_XMLRequestBody();
            inValue.Body.Tarih = Tarih;
            IETT_GUI.IBB360.GetIettYolculukHat_XMLResponse retVal = ((IETT_GUI.IBB360.ibb360Soap)(this)).GetIettYolculukHat_XML(inValue);
            return retVal.Body.GetIettYolculukHat_XMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetIettYolculukHat_XMLResponse> IETT_GUI.IBB360.ibb360Soap.GetIettYolculukHat_XMLAsync(IETT_GUI.IBB360.GetIettYolculukHat_XMLRequest request) {
            return base.Channel.GetIettYolculukHat_XMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<IETT_GUI.IBB360.GetIettYolculukHat_XMLResponse> GetIettYolculukHat_XMLAsync(string Tarih) {
            IETT_GUI.IBB360.GetIettYolculukHat_XMLRequest inValue = new IETT_GUI.IBB360.GetIettYolculukHat_XMLRequest();
            inValue.Body = new IETT_GUI.IBB360.GetIettYolculukHat_XMLRequestBody();
            inValue.Body.Tarih = Tarih;
            return ((IETT_GUI.IBB360.ibb360Soap)(this)).GetIettYolculukHat_XMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IETT_GUI.IBB360.GetIettYolculukHat_jsonResponse IETT_GUI.IBB360.ibb360Soap.GetIettYolculukHat_json(IETT_GUI.IBB360.GetIettYolculukHat_jsonRequest request) {
            return base.Channel.GetIettYolculukHat_json(request);
        }
        
        public string GetIettYolculukHat_json(string Tarih) {
            IETT_GUI.IBB360.GetIettYolculukHat_jsonRequest inValue = new IETT_GUI.IBB360.GetIettYolculukHat_jsonRequest();
            inValue.Body = new IETT_GUI.IBB360.GetIettYolculukHat_jsonRequestBody();
            inValue.Body.Tarih = Tarih;
            IETT_GUI.IBB360.GetIettYolculukHat_jsonResponse retVal = ((IETT_GUI.IBB360.ibb360Soap)(this)).GetIettYolculukHat_json(inValue);
            return retVal.Body.GetIettYolculukHat_jsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IETT_GUI.IBB360.GetIettYolculukHat_jsonResponse> IETT_GUI.IBB360.ibb360Soap.GetIettYolculukHat_jsonAsync(IETT_GUI.IBB360.GetIettYolculukHat_jsonRequest request) {
            return base.Channel.GetIettYolculukHat_jsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<IETT_GUI.IBB360.GetIettYolculukHat_jsonResponse> GetIettYolculukHat_jsonAsync(string Tarih) {
            IETT_GUI.IBB360.GetIettYolculukHat_jsonRequest inValue = new IETT_GUI.IBB360.GetIettYolculukHat_jsonRequest();
            inValue.Body = new IETT_GUI.IBB360.GetIettYolculukHat_jsonRequestBody();
            inValue.Body.Tarih = Tarih;
            return ((IETT_GUI.IBB360.ibb360Soap)(this)).GetIettYolculukHat_jsonAsync(inValue);
        }
    }
}
